version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    labels: ["A4-insubstantial"]
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: ["A4-insubstantial"]
    schedule:
      interval: "daily"
